recipe: default.v1

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: ConveRTFeaturizer
    model_url: "https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz"
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 1000
    constrain_similarities: true
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: true
  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 500
    constrain_similarities: true
    retrieval_intent: agency

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    retrieval_intent: greet

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    retrieval_intent: goodbye

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    retrieval_intent: thankyou

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    retrieval_intent: out_of_scope

  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true

assistant_id: 20230520-222229-coincident-vocoder
